spring:
  profiles:
    active: @spring.profiles.active@
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: changelogs/master-changelog.xml

server:
  error:
    include-message: always

logging:
  level:
    org:
      springframework:
        security: DEBUG