# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    hostname: localhost
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: test_db

volumes:
  postgres-data:
